[package]
name = "wasm-utils"
version = "0.1.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
edition = "2018"

[dependencies]
parity-wasm = "0.38.0"

[dev-dependencies]
wabt = "0.7.4"
