[package]
name = "sm-address"
version = "0.1.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[profile.release]
panic = "abort"
opt-level = 3
debug = false

[dependencies]
# sm-alloc = { path = "../sm-alloc" }
